EXTERN_ATOMIC PROC so.mark.channels(CHAN OF SP,CHAN OF SP) : hostio
EXTERN_ATOMIC PROC so.write.char(CHAN OF SP,CHAN OF SP,VAL BYTE) : hostio
EXTERN_ATOMIC PROC so.write.nl(CHAN OF SP,CHAN OF SP) : hostio
EXTERN_ATOMIC PROC so.write.string(CHAN OF SP,CHAN OF SP,VAL []BYTE) : hostio
EXTERN_ATOMIC PROC so.write.string.nl(CHAN OF SP,CHAN OF SP,VAL []BYTE) : hostio
EXTERN_ATOMIC PROC so.write.int(CHAN OF SP,CHAN OF SP,VAL INT,VAL INT) : hostio
EXTERN_ATOMIC PROC so.write.int32(CHAN OF SP,CHAN OF SP,VAL INT32,VAL INT) : hostio
EXTERN_ATOMIC PROC so.write.hex.int(CHAN OF SP,CHAN OF SP,VAL INT,VAL INT) : hostio
EXTERN_ATOMIC PROC so.write.hex.int32(CHAN OF SP,CHAN OF SP,VAL INT32,VAL INT) : hostio
EXTERN_ATOMIC PROC so.write.real32(CHAN OF SP,CHAN OF SP,VAL REAL32,VAL INT,VAL INT) : hostio
EXTERN_ATOMIC PROC so.write.real64(CHAN OF SP,CHAN OF SP,VAL REAL64,VAL INT,VAL INT) : hostio
EXTERN_ATOMIC PROC so.write.int64(CHAN OF SP,CHAN OF SP,VAL INT64,VAL INT) : hostio
EXTERN_ATOMIC PROC so.write.hex.int64(CHAN OF SP,CHAN OF SP,VAL INT64,VAL INT) : hostio
EXTERN_ATOMIC PROC so.fwrite.char(CHAN OF SP,CHAN OF SP,VAL INT32,VAL BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.nl(CHAN OF SP,CHAN OF SP,VAL INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.string(CHAN OF SP,CHAN OF SP,VAL INT32,VAL []BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.string.nl(CHAN OF SP,CHAN OF SP,VAL INT32,VAL []BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.int(CHAN OF SP,CHAN OF SP,VAL INT32,VAL INT,VAL INT,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.int32(CHAN OF SP,CHAN OF SP,VAL INT32,VAL INT32,VAL INT,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.hex.int(CHAN OF SP,CHAN OF SP,VAL INT32,VAL INT,VAL INT,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.hex.int32(CHAN OF SP,CHAN OF SP,VAL INT32,VAL INT32,VAL INT,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.real32(CHAN OF SP,CHAN OF SP,VAL INT32,VAL REAL32,VAL INT,VAL INT,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.real64(CHAN OF SP,CHAN OF SP,VAL INT32,VAL REAL64,VAL INT,VAL INT,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.int64(CHAN OF SP,CHAN OF SP,VAL INT32,VAL INT64,VAL INT,BYTE) : hostio
EXTERN_ATOMIC PROC so.fwrite.hex.int64(CHAN OF SP,CHAN OF SP,VAL INT32,VAL INT64,VAL INT,BYTE) : hostio
EXTERN_ATOMIC PROC MALLOC(INT32,VAL INT) : hostio
EXTERN_ATOMIC PROC FREE(INT32) : hostio
EXTERN_ATOMIC PROC STRING.OCCAM.TO.C(VAL []BYTE,VAL INT32) : hostio
EXTERN_ATOMIC PROC so.open(CHAN OF SP,CHAN OF SP,VAL []BYTE,VAL BYTE,VAL BYTE,INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.close(CHAN OF SP,CHAN OF SP,INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.test.exists(CHAN OF SP,CHAN OF SP,VAL []BYTE,BOOL) : hostio
EXTERN_ATOMIC PROC so.open.temp(CHAN OF SP,CHAN OF SP,VAL BYTE,[6]BYTE,INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.popen.read(CHAN OF SP,CHAN OF SP,VAL []BYTE,VAL []BYTE,VAL BYTE,INT,[]BYTE,INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.write(CHAN OF SP,CHAN OF SP,VAL INT32,VAL []BYTE,INT) : hostio
EXTERN_ATOMIC PROC so.read(CHAN OF SP,CHAN OF SP,VAL INT32,INT,[]BYTE) : hostio
EXTERN_ATOMIC PROC so.gets(CHAN OF SP,CHAN OF SP,VAL INT32,INT,[]BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.puts(CHAN OF SP,CHAN OF SP,VAL INT32,VAL []BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.flush(CHAN OF SP,CHAN OF SP,VAL INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.seek(CHAN OF SP,CHAN OF SP,VAL INT32,VAL INT32,VAL INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.tell(CHAN OF SP,CHAN OF SP,VAL INT32,INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.eof(CHAN OF SP,CHAN OF SP,VAL INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.ferror(CHAN OF SP,CHAN OF SP,VAL INT32,INT32,INT,[]BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.remove(CHAN OF SP,CHAN OF SP,VAL []BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.rename(CHAN OF SP,CHAN OF SP,VAL []BYTE,VAL []BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.commandline(CHAN OF SP,CHAN OF SP,VAL BYTE,INT,[]BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.parse.command.line(CHAN OF SP,CHAN OF SP,VAL [][]BYTE,VAL []INT,[]BOOL,[][2]INT,INT,[]BYTE) : hostio
EXTERN_ATOMIC PROC so.getenv(CHAN OF SP,CHAN OF SP,VAL []BYTE,INT,[]BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.time(CHAN OF SP,CHAN OF SP,INT32,INT32) : hostio
EXTERN_ATOMIC PROC so.system(CHAN OF SP,CHAN OF SP,VAL []BYTE,INT32,BYTE) : hostio
EXTERN_ATOMIC PROC so.exit(CHAN OF SP,CHAN OF SP,VAL INT32) : hostio
EXTERN_ATOMIC PROC so.core(CHAN OF SP,CHAN OF SP,VAL INT32,INT,[]BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.version(CHAN OF SP,CHAN OF SP,BYTE,BYTE,BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.getkey(CHAN OF SP,CHAN OF SP,BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.read.echo.line(CHAN OF SP,CHAN OF SP,INT,[]BYTE,BYTE) : hostio
EXTERN_ATOMIC PROC so.read.echo.int(CHAN OF SP,CHAN OF SP,INT,BOOL) : hostio
EXTERN_ATOMIC PROC sp.getkey(CHAN OF SP,CHAN OF SP,BYTE,BYTE) : hostio
