EXTERN_ATOMIC BOOL FUNCTION is.in.range(VAL BYTE,VAL BYTE,VAL BYTE) : string
EXTERN_ATOMIC BOOL FUNCTION is.upper(VAL BYTE) : string
EXTERN_ATOMIC BOOL FUNCTION is.lower(VAL BYTE) : string
EXTERN_ATOMIC BOOL FUNCTION is.digit(VAL BYTE) : string
EXTERN_ATOMIC BOOL FUNCTION is.hex.digit(VAL BYTE) : string
EXTERN_ATOMIC PROC to.upper.case(VAL []BYTE) : string
EXTERN_ATOMIC PROC to.lower.case(VAL []BYTE) : string
EXTERN_ATOMIC INT FUNCTION compare.strings(VAL []BYTE,VAL []BYTE) : string
EXTERN_ATOMIC BOOL FUNCTION eqstr(VAL []BYTE,VAL []BYTE) : string
EXTERN_ATOMIC PROC append.text(INT,[]BYTE,VAL []BYTE) : string
EXTERN_ATOMIC INT FUNCTION char.pos(VAL BYTE,VAL []BYTE) : string
