#!/bin/csh
#{{{  File banner
# @(#)=====================================================
# @(#)  Project : GPMIMD ESPRIT P5404
# @(#)  Authors : Mark Debbage, Mark Hill, Denis Nicole and Sean Wykes
# @(#)            University of Southampton
#  
# @(#)    Title : debugging script
# @(#)   System : Occam 2 C
# @(#) Filename : odebug
# @(#)  Version : 1.3
# @(#)     Date : 3/4/97
# @(#)====================================================
#}}}
set CMD=`which  $0`
set HERE=$CMD:h
if ($#argv > 0) then 
  if (-x $1) then
    gdb $* -x $HERE/occam.gdb -q
  else
    echo Could not find executable $1.
  endif
else
  echo No executable supplied.
endif
