EXTERN_ATOMIC REAL32 FUNCTION ALOG(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION ALOG10(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION EXP(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION TAN(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION SIN(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION ASIN(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION COS(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION ACOS(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION SINH(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION COSH(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION TANH(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION ATAN(VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION ATAN2(VAL REAL32,VAL REAL32) : snglmath
EXTERN_ATOMIC REAL32,INT32 FUNCTION RAN(VAL INT32) : snglmath
EXTERN_ATOMIC REAL32 FUNCTION POWER(VAL REAL32,VAL REAL32) : snglmath
