EXTERN_ATOMIC REAL64 FUNCTION DALOG(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DALOG10(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DEXP(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DTAN(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DSIN(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DASIN(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DCOS(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DACOS(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DSINH(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DCOSH(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DTANH(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DATAN(VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DATAN2(VAL REAL64,VAL REAL64) : dblmath
EXTERN_ATOMIC REAL64,INT32 FUNCTION DRAN(VAL INT32) : dblmath
EXTERN_ATOMIC REAL64 FUNCTION DPOWER(VAL REAL64,VAL REAL64) : dblmath
