EXTERN_ATOMIC PROC INTTOSTRING(INT,[]BYTE,VAL INT) : convert
EXTERN_ATOMIC PROC INT16TOSTRING(INT,[]BYTE,VAL INT16) : convert
EXTERN_ATOMIC PROC INT32TOSTRING(INT,[]BYTE,VAL INT32) : convert
EXTERN_ATOMIC PROC INT64TOSTRING(INT,[]BYTE,VAL INT64) : convert
EXTERN_ATOMIC PROC STRINGTOINT(BOOL,INT,VAL []BYTE) : convert
EXTERN_ATOMIC PROC STRINGTOINT16(BOOL,INT16,VAL []BYTE) : convert
EXTERN_ATOMIC PROC STRINGTOINT32(BOOL,INT32,VAL []BYTE) : convert
EXTERN_ATOMIC PROC STRINGTOINT64(BOOL,INT64,VAL []BYTE) : convert
EXTERN_ATOMIC PROC HTOS(INT,[]BYTE,VAL INT,VAL INT) : convert
EXTERN_ATOMIC PROC HEXTOSTRING(INT,[]BYTE,VAL INT) : convert
EXTERN_ATOMIC PROC HEX16TOSTRING(INT,[]BYTE,VAL INT16) : convert
EXTERN_ATOMIC PROC HEX32TOSTRING(INT,[]BYTE,VAL INT32) : convert
EXTERN_ATOMIC PROC HEX64TOSTRING(INT,[]BYTE,VAL INT64) : convert
EXTERN_ATOMIC PROC STRINGTOHEX(BOOL,INT,VAL []BYTE) : convert
EXTERN_ATOMIC PROC STRINGTOHEX16(BOOL,INT16,VAL []BYTE) : convert
EXTERN_ATOMIC PROC STRINGTOHEX32(BOOL,INT32,VAL []BYTE) : convert
EXTERN_ATOMIC PROC STRINGTOHEX64(BOOL,INT64,VAL []BYTE) : convert
EXTERN_ATOMIC PROC REAL32TOSTRING(INT,[]BYTE,VAL REAL32,VAL INT,VAL INT) : convert
EXTERN_ATOMIC PROC REAL64TOSTRING(INT,[]BYTE,VAL REAL64,VAL INT,VAL INT) : convert
EXTERN_ATOMIC PROC STRINGTOREAL32(BOOL,REAL32,VAL []BYTE) : convert
EXTERN_ATOMIC PROC STRINGTOREAL64(BOOL,REAL64,VAL []BYTE) : convert
EXTERN_ATOMIC PROC STRINGTOBOOL(BOOL,BOOL,VAL []BYTE) : convert
EXTERN_ATOMIC PROC BOOLTOSTRING(INT,[]BYTE,VAL BOOL) : convert
