EXTERN_ATOMIC INT FUNCTION LONGADD(VAL INT,VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT FUNCTION LONGSUB(VAL INT,VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT FUNCTION ASHIFTRIGHT(VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT FUNCTION ASHIFTLEFT(VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT FUNCTION ROTATERIGHT(VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT FUNCTION ROTATELEFT(VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT,INT FUNCTION LONGSUM(VAL INT,VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT,INT FUNCTION LONGDIFF(VAL INT,VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT,INT FUNCTION LONGPROD(VAL INT,VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT,INT FUNCTION LONGDIV(VAL INT,VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT,INT FUNCTION SHIFTRIGHT(VAL INT,VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT,INT FUNCTION SHIFTLEFT(VAL INT,VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT,INT,INT FUNCTION NORMALISE(VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC REAL32 FUNCTION ABS(VAL REAL32) : Intrinsics
EXTERN_ATOMIC REAL64 FUNCTION DABS(VAL REAL64) : Intrinsics
EXTERN_ATOMIC REAL32 FUNCTION SCALEB(VAL REAL32,VAL INT) : Intrinsics
EXTERN_ATOMIC REAL64 FUNCTION DSCALEB(VAL REAL64,VAL INT) : Intrinsics
EXTERN_ATOMIC REAL32 FUNCTION COPYSIGN(VAL REAL32,VAL REAL32) : Intrinsics
EXTERN_ATOMIC REAL64 FUNCTION DCOPYSIGN(VAL REAL64,VAL REAL64) : Intrinsics
EXTERN_ATOMIC REAL32 FUNCTION SQRT(VAL REAL32) : Intrinsics
EXTERN_ATOMIC REAL64 FUNCTION DSQRT(VAL REAL64) : Intrinsics
EXTERN_ATOMIC REAL64 FUNCTION DNEXTAFTER(VAL REAL64,VAL REAL64) : Intrinsics
EXTERN_ATOMIC REAL32 FUNCTION REAL32OP(VAL REAL32,VAL INT,VAL REAL32) : Intrinsics
EXTERN_ATOMIC REAL64 FUNCTION REAL64OP(VAL REAL64,VAL INT,VAL REAL64) : Intrinsics
EXTERN_ATOMIC BOOL,REAL32 FUNCTION IEEE32OP(VAL REAL32,VAL INT,VAL INT,VAL REAL32) : Intrinsics
EXTERN_ATOMIC BOOL,REAL64 FUNCTION IEEE64OP(VAL REAL64,VAL INT,VAL INT,VAL REAL64) : Intrinsics
EXTERN_ATOMIC REAL32 FUNCTION REAL32REM(VAL REAL32,VAL REAL32) : Intrinsics
EXTERN_ATOMIC REAL64 FUNCTION REAL64REM(VAL REAL64,VAL REAL64) : Intrinsics
EXTERN_ATOMIC BOOL,REAL32 FUNCTION IEEE32REM(VAL REAL32,VAL REAL32) : Intrinsics
EXTERN_ATOMIC BOOL,REAL64 FUNCTION IEEE64REM(VAL REAL64,VAL REAL64) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION REAL32EQ(VAL REAL32,VAL REAL32) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION REAL64EQ(VAL REAL64,VAL REAL64) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION REAL32GT(VAL REAL32,VAL REAL32) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION REAL64GT(VAL REAL64,VAL REAL64) : Intrinsics
EXTERN_ATOMIC INT FUNCTION IEEECOMPARE(VAL REAL32,VAL REAL32) : Intrinsics
EXTERN_ATOMIC INT FUNCTION DIEEECOMPARE(VAL REAL64,VAL REAL64) : Intrinsics
EXTERN_ATOMIC REAL32 FUNCTION LOGB(VAL REAL32) : Intrinsics
EXTERN_ATOMIC REAL32 FUNCTION DLOGB(VAL REAL64) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION ISNAN(VAL REAL32) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION DISNAN(VAL REAL64) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION NOTFINITE(VAL REAL32) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION DNOTFINITE(VAL REAL64) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION ORDERED(VAL REAL32,VAL REAL32) : Intrinsics
EXTERN_ATOMIC BOOL FUNCTION DORDERED(VAL REAL64,VAL REAL64) : Intrinsics
EXTERN_ATOMIC INT FUNCTION BITCOUNT(VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT FUNCTION BITREVNBITS(VAL INT,VAL INT) : Intrinsics
EXTERN_ATOMIC INT FUNCTION BITREVWORD(VAL INT) : Intrinsics
EXTERN_ATOMIC PROC ASSERT(VAL BOOL) : Intrinsics
EXTERN_ATOMIC PROC CAUSEERROR() : Intrinsics
EXTERN_OCCAM PROC RESCHEDULE() : Intrinsics
